export { default as SearchMajor } from "./SearchMajor.svelte"
export { default as CustomersMajor } from "./CustomersMajor.svelte"
export { default as CartMajor } from "./CartMajor.svelte"
export { default as CaretDownMinor } from "./CaretDownMinor.svelte"
export { default as CaretUpMinor } from "./CaretUpMinor.svelte"
